@host=http://localhost:3000

@remote=http://localhost:3000
#https://bunhono-nqw9skkk.b4a.run/

###
POST {{remote}}/api/auth/login
Content-Type: application/json

{
    "username":"Amie58@yahoo.com",
    "password":"use1"
}


###
GET {{remote}}/api/auth/me
Cookie: 

###
GET {{remote}}/api/users

###
GET {{remote}}/api/users/2001


###
POST {{remote}}/api/users
Content-Type: application/json

{
    "fullName":"sagar",
    "password":"use1",
    "email":"sagar5@gmail.com",
    "roles":"admin",
    "phone":"99-999-999"
}