version: "3"

services:
  # app:
  #   restart: "always"
  #   build:
  #     context: .
  #     dockerfile: dev.Dockerfile
  #   command: bun dev
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://todoapp:todo123@postgres/todos
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: suraj
      POSTGRES_DB: postgres
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - 5432:5432
